[package]
name = "dht"
version = "0.1.0"
edition = "2021"

[build-dependencies]
protobuf-codegen = "3.5.1"

[dependencies]
crc = "3.2.1"
protobuf = "3.5.1"
rand = "0.8"

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "server"
path = "src/server.rs"
