[package]
name = "dht"
version = "0.1.0"
edition = "2021"

[build-dependencies]
protobuf-codegen = "3.5.1"

[dependencies]
chrono = "0.4"
crc = "3.2.1"
log = "0.4.22"
log4rs = "1.3.0"
protobuf = "3.5.1"
rand = "0.8"

[[bin]]
name = "client"
path = "src/client.rs"
